### ISSUE TITLE
How can i get polygonize0529.exe

### ISSUE THREAD

**Issue by shiyue-code** [SonwYang/SLP-cropland-parcel-extraction#5]
How can i get polygonize0529.exe

**Comment by shiyue-code** [comment]
i use  gdalTools.raster2poly instead

**Comment by githubwys** [comment]
> i used gdalTools.raster2poly instead

hi, could you please explain how to use "gdalTools.raster2poly" in Ubuntu sys.
how to change the code
the polygonize0529.exe only can be used in Win.

seems:
`# polygonize(imgPath, out_skeleton_path, shpPath)
gdalTools.raster2poly(out_skeleton_path, shpPath)`
