### ISSUE TITLE
关于训练结果的一些疑问

### ISSUE THREAD

**Issue by shiyue-code** [SonwYang/SLP-cropland-parcel-extraction#6]
您好，我这边看到训练集是包含测试集的，我认为这可能会会导致数据偏高。请问论文中的数据,测试数据是否是单独分开的，不包含于训练集中？

**Comment by SonwYang** [comment]
测试集都是单独的大图，没有裁剪过，且没有在训练集中出现过，你看的是验证集吧

**Comment by shiyue-code** [comment]
> 测试集都是一个人大图，没有裁剪过，没有在训练集中出现过，你看的就是验证集吧

不好意思，描述错误，是验证集。我看很多代码val dataset 也是都不会包含在train dataset之内的。

**Comment by SonwYang** [comment]
代码会在线划分训练集和验证集，不存在你说的那种情况。
