### ISSUE TITLE
Merging predictions is not working

### ISSUE THREAD

**Issue by jorgelerre** [SonwYang/SLP-cropland-parcel-extraction#8]
Hello, SonwYang.

I'm trying to use your model with the following image: 
![image](https://github.com/user-attachments/assets/cb845586-d5b9-4909-ac4d-173f70e41d83)

However, the output for the edge detection is this:
![image](https://github.com/user-attachments/assets/1331e7af-1456-49ff-9d00-9e81a4e6eaa4)

I saw that the prediction is generated by merging some modifications of the image (flipping, using mirror padding, etc.), done in input_and_output function. I will try to fix it by myself, but it feels pretty strange that it worked for you properly. May I be doing something wrong?

**Comment by SonwYang** [comment]
@jorgelerre Is this model params trained form your datatset or mine?

**Comment by SonwYang** [comment]
If you want to get good results, you must train your model based your dataset. Mine model params is trained based on sentinel-2 image.

**Comment by jorgelerre** [comment]
@SonwYang I'm using your weights to run the model. However, I took the image from your drive (in the polygonize zip you have some patches, the one I tried was temp_pic/0_0.png), so I suppose it was extracted from Sentinel-2 too.

**Comment by SonwYang** [comment]
No, this image is not sentinel-2. Actually, this is china statellite image.
